In [1]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [2]:
k = 5

In [3]:
df=pd.read_csv("data_final_linear.csv")

In [4]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [5]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([2, 1, 3, ..., 1, 3, 2], dtype=int32)

In [6]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8429107824692593


In [7]:
ypred = kmeans.predict(X)
print(ypred)

[2 1 3 ... 1 3 2]


In [8]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [9]:
n = X.shape[0]
distances = np.zeros((n,k))
d = X.shape[1]
clusters = np.zeros(n)
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [10]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

224.02151387171045


In [11]:
iteration = 0
force = False
while (error != 0) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            centers_old = np.zeros([k,d])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    print("FLAG=",force)
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print(iteration)
    if error == 0 and force == False:
        break

FLAG= True
259.8194261893217
1
FLAG= True
185.7052608118208
2
FLAG= True
208.65299354883075
3
FLAG= True
329.39031563612633
4
FLAG= True
212.70235279379875
5
FLAG= True
266.0978345980229
6
FLAG= True
217.53952441997953
7
FLAG= True
225.65127368258513
8
FLAG= True
206.5446556738723
9
FLAG= True
177.7176045259859
10
FLAG= True
222.11475427230457
11
FLAG= False
264.71500389295574
12
FLAG= False
25.532822893997583
13
FLAG= False
9.103880904536243
14
FLAG= False
5.567120997252347
15
FLAG= False
3.9234962641869155
16
FLAG= False
2.8163210408066695
17
FLAG= False
2.0058557108369204
18
FLAG= False
1.542694199700173
19
FLAG= False
1.1000058151226386
20
FLAG= False
0.8084091298590517
21
FLAG= False
0.6326127875443195
22
FLAG= False
0.46146927392123566
23
FLAG= False
0.35352182304345836
24
FLAG= False
0.25801399395091734
25
FLAG= False
0.22417148296782655
26
FLAG= False
0.18611863628738615
27
FLAG= False
0.14363428401598652
28
FLAG= False
0.12669451088349604
29
FLAG= False
0.1050012009167001
30
F

In [12]:
# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

In [13]:
clusters

# centers_new

array([4, 3, 1, ..., 3, 1, 4])

In [14]:
cont = contingency_matrix(clusters,Y)
print(cont)

[[50077  2404   566  4323    26]
 [    0 26689     0   293     0]
 [   26  7378     0  2174     0]
 [ 2842  7278    10  3765     3]
 [14398  2178   419  1101    23]]


In [15]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8400212744000699
