In [1]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [2]:
k = 5

In [3]:
df=pd.read_csv("data_final_linear.csv")

In [4]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [5]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([1, 2, 0, ..., 2, 0, 1], dtype=int32)

In [6]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8597080326736681


In [7]:
ypred = kmeans.predict(X)
print(ypred)

[1 2 0 ... 2 0 1]


In [8]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [9]:
n = X.shape[0]
distances = np.zeros((n,k))
d = X.shape[1]
clusters = np.zeros(n)
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [10]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

15.4983867165815


In [11]:
iteration = 0
force = False
while (error != 0 or force==True) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            iteration = 0
            centers_old = np.zeros([k,c])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    print("FLAG=",force)
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print(iteration)
    if error == 0 and force == False:
        break

FLAG= False
20.342433999034903
1
FLAG= False
2.6936761264818845
2
FLAG= False
0.797085293244497
3
FLAG= False
0.3100356404883071
4
FLAG= False
0.10852626418627684
5
FLAG= False
0.08047466572648837
6
FLAG= False
0.05933688652787887
7
FLAG= False
0.04557624320955119
8
FLAG= False
0.0351048843086688
9
FLAG= False
0.028631038115167505
10
FLAG= False
0.026457198538945195
11
FLAG= False
0.022369644053553447
12
FLAG= False
0.01995161634672556
13
FLAG= False
0.018762389981721493
14
FLAG= False
0.016768614813106424
15
FLAG= False
0.01653832305505315
16
FLAG= False
0.014730195100019747
17
FLAG= False
0.013376085243794805
18
FLAG= False
0.011916460465404956
19
FLAG= False
0.01018217167337378
20
FLAG= False
0.008550495474424406
21
FLAG= False
0.006969500195581915
22
FLAG= False
0.006996611040876335
23
FLAG= False
0.00593924659360219
24
FLAG= False
0.004187594560319947
25
FLAG= False
0.004511748086708261
26
FLAG= False
0.0043594582115977455
27
FLAG= False
0.0027117401858996635
28
FLAG= False
0.0013

In [12]:
# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

In [13]:
clusters

# centers_new

array([4, 4, 3, ..., 4, 3, 4])

In [14]:
cont = contingency_matrix(clusters,Y)
print(cont)

[[51991  2271   628  4328    29]
 [   27     0     0     0     0]
 [  548  6974     0  5407     0]
 [   82 34210     2   491     0]
 [14695  2472   365  1430    23]]


In [15]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8565089344542084
