In [1]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [2]:
k = 5

In [3]:
df=pd.read_csv("data_final_linear.csv")

In [4]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [5]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([3, 4, 1, ..., 4, 1, 3], dtype=int32)

In [6]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8597000944646869


In [7]:
ypred = kmeans.predict(X)
print(ypred)

[3 4 1 ... 4 1 3]


In [8]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [9]:
n = X.shape[0]
distances = np.zeros((n,k))
d = X.shape[1]
clusters = np.zeros(n)
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [10]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

12.075676711772934


In [11]:
iteration = 0
force = False
while (error != 0) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            centers_old = np.zeros([k,d])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    print("FLAG=",force)
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print(iteration)
    if error == 0 and force == False:
        break

FLAG= False
42.3188179071985
1
FLAG= False
20.560387679536348
2
FLAG= False
0.8119738346812517
3
FLAG= False
0.31984477507641995
4
FLAG= False
0.08263596710123386
5
FLAG= False
0.06492753464706952
6
FLAG= False
0.03710020023264835
7
FLAG= False
0.017746257813231324
8
FLAG= False
0.00763513480002961
9
FLAG= False
0.0032611477146869574
10
FLAG= False
0.0007807605916391545
11
FLAG= False
0.0
12


In [12]:
# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

In [13]:
clusters

# centers_new

array([1, 4, 3, ..., 4, 3, 1])

In [14]:
cont = contingency_matrix(clusters,Y)
print(cont)

[[    1     0     0     0     0]
 [62843  4269   933  4810    42]
 [   34     0     0     0     0]
 [   44 34151     0   504     0]
 [ 4421  7507    62  6342    10]]


In [15]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8298286140680939
