In [35]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [36]:
df=pd.read_csv("data_final_linear.csv")
k = 5

In [37]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [38]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([1, 1, 0, ..., 3, 0, 3], dtype=int32)

In [39]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.86833686583633

In [40]:
ypred = kmeans.predict(X)
print(ypred)

[1 1 0 ... 3 0 3]


In [41]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [42]:
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [43]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

9.860069087411352


In [44]:
iteration = 0
force = False
while (error != 0 or force==True) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            iteration = 0
            centers_old = np.zeros([k,c])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print("FLAG=",force)
    print(iteration)
    if error == 0 and force == False:
        break

41.33514240550831
FLAG= False
1
20.87119898229321
FLAG= False
2
0.3270031528766488
FLAG= False
3
0.3108476359209702
FLAG= False
4
0.3360709940266399
FLAG= False
5
0.2554537536824689
FLAG= False
6
0.1786017999978293
FLAG= False
7
0.08693847229178335
FLAG= False
8
0.04197711730764744
FLAG= False
9
0.02083956384316426
FLAG= False
10
0.011037790247720546
FLAG= False
11
0.006004599369407853
FLAG= False
12
0.0026552335612758425
FLAG= False
13
0.001120469130713457
FLAG= False
14
0.0005521823141298113
FLAG= False
15
0.0001588151971397179
FLAG= False
16
7.935215671832466e-05
FLAG= False
17
0.0
FLAG= False
18


In [45]:
# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

In [46]:
clusters

# centers_new

array([4, 4, 2, ..., 0, 2, 0])

In [47]:
cont = contingency_matrix(clusters,Y)
cont

array([[49204,  1542,    55,   322,     2],
       [ 2794,  6895,    51,  5222,     0],
       [  112, 34237,     1,     4,     0],
       [    1,     0,     0,     0,     0],
       [15232,  3253,   888,  6108,    50]])

In [48]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8380287839457662