In [15]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [16]:
df=pd.read_csv("data_final.csv")
k = 5

In [17]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [18]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([0, 0, 1, ..., 0, 1, 0], dtype=int32)

In [19]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8581838965492605

In [20]:
ypred = kmeans.predict(X)
print(ypred)

[0 0 1 ... 0 1 0]


In [21]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [22]:
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [23]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

12.026085585528868


In [24]:
iteration = 0
force = False
while (error != 0 or force==True) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            iteration = 0
            centers_old = np.zeros([k,c])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print("FLAG=",force)
    print(iteration)
    if error == 0 and force == False:
        break

6.820658963794813
FLAG= False
1
2.5257026321585108
FLAG= False
2
1.1956677986891129
FLAG= False
3
0.5586650837188977
FLAG= False
4
0.3697584789517478
FLAG= False
5
0.25895349177536897
FLAG= False
6
0.3573921846072222
FLAG= False
7
0.4460802699465346
FLAG= False
8
0.22903768141268416
FLAG= False
9
0.080723780807503
FLAG= False
10
0.10500521821141073
FLAG= False
11
0.06873655157707824
FLAG= False
12
0.02742458229949186
FLAG= False
13
0.08918707948640478
FLAG= False
14
0.16958780818925362
FLAG= False
15
0.04897084061468801
FLAG= False
16
0.030586848047525837
FLAG= False
17
0.02562582959691411
FLAG= False
18
0.024854717047160274
FLAG= False
19
0.02433044992160889
FLAG= False
20
0.017275033561236337
FLAG= False
21
0.010433403691980342
FLAG= False
22
0.005612800059256087
FLAG= False
23
0.00347549467539363
FLAG= False
24
0.0017165304111025795
FLAG= False
25
0.0010780234518646735
FLAG= False
26
0.001239119518457146
FLAG= False
27
0.0009235371958311698
FLAG= False
28
0.0007499397378883906
FLAG=

In [25]:
# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

In [26]:
clusters

# centers_new

array([4, 4, 1, ..., 4, 1, 4])

In [27]:
cont = contingency_matrix(clusters,Y)
cont

array([[41317,  2240,    10,     4,     0],
       [   81, 34213,     0,    38,     0],
       [11225,   569,   573,  4301,    28],
       [  313,  6889,     0,  5041,     0],
       [14407,  2016,   412,  2272,    24]])

In [28]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.857731418637327