In [29]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [30]:
df=pd.read_csv("data_final.csv")
k = 5

In [31]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [32]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([0, 0, 3, ..., 0, 3, 0], dtype=int32)

In [33]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8570963619188239

In [34]:
ypred = kmeans.predict(X)
print(ypred)

[0 0 3 ... 0 3 0]


In [35]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [36]:
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [37]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

12.723273381378522


In [38]:
iteration = 0
force = False
while (error != 0 or force==True) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            iteration = 0
            centers_old = np.zeros([k,c])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print("FLAG=",force)
    print(iteration)
    if error == 0 and force == False:
        break

5.857852841370847
FLAG= False
1
2.468202803909863
FLAG= False
2
0.7556946946455609
FLAG= False
3
0.32397129368776956
FLAG= False
4
0.0872754525400174
FLAG= False
5
0.13633895177841934
FLAG= False
6
0.07497249119966232
FLAG= False
7
0.021993698675671577
FLAG= False
8
0.00693464513584034
FLAG= False
9
0.0033583298777625195
FLAG= False
10
0.0007125762102812095
FLAG= False
11
0.00025885703670085484
FLAG= False
12
8.377158416414938e-05
FLAG= False
13
0.0
FLAG= False
14


In [39]:
# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

In [40]:
clusters

# centers_new

array([3, 2, 0, ..., 0, 4, 1])

In [41]:
cont = contingency_matrix(clusters,Y)
cont

array([[  869, 22348,     1,   323,     0],
       [27064,  3349,   308,   336,     6],
       [ 2763,  7229,    54,  6463,     4],
       [36264,  1054,   629,  4465,    42],
       [  383, 11947,     3,    69,     0]])

In [42]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
purity

0.8323370881061815