In [1]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [2]:
k = 5

In [3]:
df=pd.read_csv("data_final_linear.csv")

In [4]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [5]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([0, 2, 1, ..., 2, 1, 0], dtype=int32)

In [6]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8597000944646869


In [7]:
ypred = kmeans.predict(X)
print(ypred)

[0 2 1 ... 2 1 0]


In [8]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [9]:
n = X.shape[0]
distances = np.zeros((n,k))
d = X.shape[1]
clusters = np.zeros(n)
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [10]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

15.11329092835582


In [11]:
iteration = 0
force = False
while (error != 0) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            centers_old = np.zeros([k,d])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    print("FLAG=",force)
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print(iteration)
    if error == 0 and force == False:
        break

FLAG= True
13.592642735776788
1
FLAG= False
38.97241645849547
2
FLAG= False
19.842848741626135
3
FLAG= False
0.4259991883613718
4
FLAG= False
0.09310455903263751
5
FLAG= False
0.06728116185359216
6
FLAG= False
0.053776785773878
7
FLAG= False
0.04427972999518229
8
FLAG= False
0.03980786786805895
9
FLAG= False
0.036778276008074706
10
FLAG= False
0.032313944890408876
11
FLAG= False
0.03497012497670612
12
FLAG= False
0.029886810618389707
13
FLAG= False
0.02590171419820986
14
FLAG= False
0.021936578286142573
15
FLAG= False
0.01863006116979514
16
FLAG= False
0.013115262589400772
17
FLAG= False
0.013662190386593763
18
FLAG= False
0.01014454961392053
19
FLAG= False
0.007965370443737877
20
FLAG= False
0.006598661944474272
21
FLAG= False
0.005865696668835766
22
FLAG= False
0.0033861839373911192
23
FLAG= False
0.003649197658836754
24
FLAG= False
0.0024147222366093374
25
FLAG= False
0.0021631386821769397
26
FLAG= False
0.0021249942961515025
27
FLAG= False
0.002419372036969507
28
FLAG= False
0.0015

In [12]:
# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

In [13]:
clusters

# centers_new

array([3, 3, 0, ..., 3, 0, 3])

In [14]:
cont = contingency_matrix(clusters,Y)
print(cont)

[[   82 34210     2   491     0]
 [    1     0     0     0     0]
 [  549  6974     0  5407     0]
 [14705  2472   365  1430    23]
 [52006  2271   628  4328    29]]


In [15]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8565009962452271
