In [1]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [2]:
k = 5

In [3]:
df=pd.read_csv("data_final_deep.csv")
# df

In [4]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [5]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_
X

array([[0.84902177, 0.8448608 , 0.84308496, ..., 0.85015785, 0.84556021,
        0.84667182],
       [0.80426793, 0.80019638, 0.79827975, ..., 0.80592719, 0.80110199,
        0.8025164 ],
       [0.78803915, 0.78406033, 0.78170094, ..., 0.78968705, 0.78495992,
        0.78600073],
       ...,
       [0.83265752, 0.82842734, 0.82666033, ..., 0.83400816, 0.82922069,
        0.83028288],
       [0.79071004, 0.78668971, 0.7842709 , ..., 0.79223445, 0.78757703,
        0.78860465],
       [0.84998933, 0.84581503, 0.84409876, ..., 0.85112144, 0.84653713,
        0.84767035]])

In [6]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
print(cn)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

[[ 3676 33765     9  1429     1]
 [55984  2112   679  4327    30]
 [   49     0     0  2720     0]
 [ 7553  3165   258   884    21]
 [   81  6885    49  2296     0]]
0.8486501075627317


In [7]:
ypred = kmeans.predict(X)
print(ypred)

[1 0 0 ... 3 0 1]


In [8]:
X.shape

(125973, 14)

In [9]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [10]:
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [11]:
d

14

In [12]:
print(centers_old.shape)
print(centers_new.shape)

(5, 14)
(5, 14)


In [13]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

15.624605125174371


In [14]:
iteration = 0
force = False
while (error != 0) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        print("M=",member)
        if member == 0:
#             pass
            force = True
#             iteration = 0
            centers_old = np.zeros([k,d])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
#     print("d=",d)
    print("FLAG = ",force)
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print(iteration)
    if error == 0 and force == False:
        break

M= 0
FLAG =  True
15.429819972009351
1
M= 0
FLAG =  True
15.380431307613797
2
M= 0
FLAG =  True
15.4398092434211
3
M= 0
FLAG =  True
15.499746261199492
4
M= 0
FLAG =  True
15.392096552626008
5
M= 0
FLAG =  True
15.500416788639516
6
M= 48393
M= 0
FLAG =  True
15.390688232721864
7
M= 0
FLAG =  True
15.229075690162894
8
M= 0
FLAG =  True
15.329127134342096
9
M= 0
FLAG =  True
15.15701934642129
10
M= 0
FLAG =  True
15.290041126617286
11
M= 50746
M= 0
FLAG =  True
15.50652324880134
12
M= 0
FLAG =  True
15.437899185516363
13
M= 51656
M= 1795
M= 72522
M= 0
FLAG =  True
15.43057332591399
14
M= 28213
M= 0
FLAG =  True
15.632838229943573
15
M= 0
FLAG =  True
15.518282353718504
16
M= 55477
M= 58156
M= 12340
M= 0
FLAG =  True
15.372553293584414
17
M= 74696
M= 0
FLAG =  True
15.436220096116834
18
M= 60133
M= 0
FLAG =  True
15.461672734515634
19
M= 20647
M= 48877
M= 0
FLAG =  True
15.238468497793743
20
M= 0
FLAG =  True
15.386981865694086
21
M= 0
FLAG =  True
15.554406931608455
22
M= 26077
M= 33775


In [15]:
# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

In [16]:
clusters

# centers_new

array([1, 4, 4, ..., 3, 4, 1])

In [17]:
cont = contingency_matrix(clusters,Y)
print(cont)

[[   81  6885    49  2296     0]
 [55860  2093   672  4325    30]
 [   49     0     0  2720     0]
 [ 7644  3169   264   882    21]
 [ 3709 33780    10  1433     1]]


In [18]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8485072198010685
