In [1]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [2]:
k = 5

In [3]:
df=pd.read_csv("data_final.csv")

In [4]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [5]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([0, 0, 1, ..., 0, 1, 0], dtype=int32)

In [6]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8355758773705476


In [7]:
ypred = kmeans.predict(X)
print(ypred)

[0 0 1 ... 0 1 0]


In [8]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [9]:
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [10]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

13.969050499099186


In [11]:
iteration = 0
force = False
while (error != 0) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            centers_old = np.zeros([k,d])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    print("FLAG=",force)
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print(iteration)
    if error == 0 and force == False:
        break

FLAG= False
7.060325616952259
1
FLAG= False
2.9175790368242893
2
FLAG= False
0.8163945482291026
3
FLAG= False
0.2843247789188579
4
FLAG= False
0.18330984226633096
5
FLAG= False
0.12375771648142939
6
FLAG= False
0.06602752402827516
7
FLAG= False
0.032739956319792644
8
FLAG= False
0.01894681200492163
9
FLAG= False
0.011740224855030585
10
FLAG= False
0.006940217037349315
11
FLAG= False
0.004826194169553552
12
FLAG= False
0.0028578453354858226
13
FLAG= False
0.001839315099522579
14
FLAG= False
0.0013861191097382381
15
FLAG= False
0.0014943173008790736
16
FLAG= False
0.0009376684777802219
17
FLAG= False
0.0005919621306387391
18
FLAG= False
0.00016405841957208868
19
FLAG= False
0.0001725324266728388
20
FLAG= False
5.253946262701697e-05
21
FLAG= False
0.0
22


In [12]:
# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

In [13]:
clusters

# centers_new

array([4, 4, 1, ..., 4, 1, 4])

In [14]:
cont = contingency_matrix(clusters,Y)
print(cont)

[[22501  2398    61   129     0]
 [  131 34289     1   297     0]
 [ 3205  6964    55  5291     2]
 [25235   327     3  1098     2]
 [16271  1949   875  4841    48]]


In [15]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8355758773705476
