In [27]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [28]:
k = 5

In [29]:
df=pd.read_csv("data_final.csv")

In [30]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [31]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([3, 3, 1, ..., 3, 1, 3], dtype=int32)

In [32]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.83454391020298


In [33]:
ypred = kmeans.predict(X)
print(ypred)

[3 3 1 ... 3 1 3]


In [34]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [35]:
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [36]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

11.739770473152312


In [37]:
iteration = 0
force = False
while (error != 0 or force==True) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            iteration = 0
            centers_old = np.zeros([k,c])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    print("FLAG=",force)
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print(iteration)
    if error == 0 and force == False:
        break

FLAG= False
5.453681449087973
1
FLAG= False
2.2857921165670065
2
FLAG= False
0.8945568998813627
3
FLAG= False
0.2637781302322079
4
FLAG= False
0.14567919034488408
5
FLAG= False
0.10087220824499168
6
FLAG= False
0.07073575221187177
7
FLAG= False
0.03604959287821525
8
FLAG= False
0.027661921121229838
9
FLAG= False
0.022425787386937734
10
FLAG= False
0.017319876890047346
11
FLAG= False
0.013559475465448018
12
FLAG= False
0.01186936185097946
13
FLAG= False
0.012256523632525438
14
FLAG= False
0.014290856598325054
15
FLAG= False
0.0196336575944402
16
FLAG= False
0.014630638817808947
17
FLAG= False
0.011677738301041438
18
FLAG= False
0.008951963586171731
19
FLAG= False
0.007334026458903105
20
FLAG= False
0.005740974255725323
21
FLAG= False
0.005058892585102177
22
FLAG= False
0.002942463904983002
23
FLAG= False
0.0017281146586666065
24
FLAG= False
0.0011961451899472337
25
FLAG= False
0.0006246252198248135
26
FLAG= False
0.00042099869694751306
27
FLAG= False
0.00034759137873254496
28
FLAG= Fals

In [38]:
# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

In [39]:
clusters

# centers_new

array([4, 4, 3, ..., 4, 3, 4])

In [40]:
cont = contingency_matrix(clusters,Y)
print(cont)

[[37564  2294     4     1     0]
 [ 2516  6923    54  5286     2]
 [11210   227   471  4054    10]
 [  148 34250     2   252     0]
 [15905  2233   464  2063    40]]


In [41]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8402752970874712
