In [1]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [2]:
k = 5

In [3]:
df=pd.read_csv("data_final.csv")

In [4]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [5]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_

array([0, 0, 1, ..., 0, 1, 0], dtype=int32)

In [6]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8362268105070134


In [7]:
ypred = kmeans.predict(X)
print(ypred)

[0 0 1 ... 0 1 0]


In [8]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [9]:
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [10]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

14.338608020564596


In [11]:
iteration = 0
force = False
while (error != 0) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        if member == 0:
            force = True
            centers_old = np.zeros([k,d])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
    print("FLAG=",force)
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print(iteration)
    if error == 0 and force == False:
        break

FLAG= False
6.04469025013426
1
FLAG= False
1.8073259228647602
2
FLAG= False
1.5450793782302294
3
FLAG= False
0.36178949679959654
4
FLAG= False
0.3388625907074003
5
FLAG= False
0.3879585849546164
6
FLAG= False
0.18701355377067258
7
FLAG= False
0.07663550860308638
8
FLAG= False
0.031792532112640645
9
FLAG= False
0.010281826088261562
10
FLAG= False
0.002904195113570431
11
FLAG= False
0.0009602322405099682
12
FLAG= False
0.00018126503583936295
13
FLAG= False
0.0001630519467343855
14
FLAG= False
0.0
15


In [12]:
# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

In [13]:
clusters

# centers_new

array([1, 1, 0, ..., 1, 0, 1])

In [14]:
cont = contingency_matrix(clusters,Y)
print(cont)

[[  170 34246     1   229     0]
 [17053  1370   935  5016    49]
 [ 3103  7026    55  5308     3]
 [ 7252  2753     0   173     0]
 [39765   532     4   930     0]]


In [15]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8362268105070134
