In [1]:
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn.metrics.cluster import contingency_matrix
import numpy as np
import pandas as pd
import random
import math
import copy

In [2]:
k = 5

In [3]:
df=pd.read_csv("data_final_deep.csv")
# df

In [4]:
Y = []
for i in df['xAttack']:
    if i=="normal":
        Y.append(0)
    elif i=="dos":
        Y.append(1)
    elif i=="r2l":
        Y.append(2)
    elif i=="probe":
        Y.append(3)
    elif i=="u2r":
        Y.append(4)

In [5]:
X = df.iloc[:,0:14].values
kmeans = KMeans(n_clusters=5).fit(X)
kmeans.labels_
X

array([[0.84672853, 0.84292277, 0.8487136 , ..., 0.84943555, 0.84423653,
        0.84673377],
       [0.80146117, 0.7977365 , 0.80342365, ..., 0.80385252, 0.79889285,
        0.80133908],
       [0.7861793 , 0.78290439, 0.78857732, ..., 0.78918644, 0.78420495,
        0.78644808],
       ...,
       [0.83039319, 0.82673528, 0.83251241, ..., 0.83331254, 0.82810635,
        0.83050308],
       [0.7890091 , 0.78561924, 0.79135719, ..., 0.79189258, 0.78689253,
        0.78920383],
       [0.84796582, 0.84412554, 0.84988619, ..., 0.85059554, 0.84539483,
        0.84794608]])

In [6]:
kmeans.cluster_centers_
cn = contingency_matrix(kmeans.labels_,Y)
print(cn)
ans = 0
for i in cn:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

[[56433  2148   803  4330    30]
 [ 3797 33682     9  1432     2]
 [   49     0     0  2741     0]
 [   86  6887    50  2290     0]
 [ 6978  3210   133   863    20]]
0.8471736006922118


In [7]:
ypred = kmeans.predict(X)
print(ypred)

[0 1 1 ... 4 1 0]


In [8]:
X.shape

(125973, 14)

In [9]:
def euclid(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [10]:
n = X.shape[0]
d = X.shape[1]
clusters = np.zeros(n)
distances = np.zeros((n,k))
mean = np.mean(X, axis = 0)
std = np.std(X, axis = 0)
centers_new = np.random.randn(k,d)*std + mean
centers_old = np.zeros([k,d])

In [11]:
d

14

In [12]:
print(centers_old.shape)
print(centers_new.shape)

(5, 14)
(5, 14)


In [13]:
error = 0
for i in range(5):
    error = error + euclid(centers_new[i], centers_old[i])

print(error)

15.435037718168127


In [14]:
iteration = 0
force = False
while (error != 0) or iteration<1000:
    force = False
    for i in range(k):
        distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
    clusters = np.argmin(distances, axis = 1)
    
    centers_old = copy.deepcopy(centers_new)
    for i in range(k):
        member = 0
        new_center = [0] * d
        
        for c in range(len(clusters)):
            if clusters[c] == i:
                member = member + 1
                for j in range(0,d):
                    new_center[j] += X[c][j]
        
        print("M=",member)
        if member == 0:
#             pass
            force = True
#             iteration = 0
            centers_old = np.zeros([k,d])
            centers_new = np.random.randn(k,d)*std + mean
            break
        else:
            new_center = np.array(new_center)
            centers_new[i] = new_center/member
        
#     print("d=",d)
    print("FLAG = ",force)
    error = 0
    for i in range(5):
        error = error + euclid(centers_new[i], centers_old[i])
    iteration = iteration + 1
    print(error)
    print(iteration)
    if error == 0 and force == False:
        break

M= 0
FLAG= True
15.589033955480282
1
M= 1431
M= 40108
M= 0
FLAG= True
15.379291902875302
2
M= 71212
M= 15
M= 54746
M= 0
FLAG= True
15.333722748675896
3
M= 0
FLAG= True
15.54113170788923
4
M= 44709
M= 62990
M= 0
FLAG= True
15.436207430820723
5
M= 73369
M= 0
FLAG= True
15.282999797796709
6
M= 72572
M= 1
M= 53400
M= 0
FLAG= True
15.435076653255562
7
M= 0
FLAG= True
15.350468249160148
8
M= 45606
M= 119
M= 80248
M= 0
FLAG= True
15.546375267995966
9
M= 0
FLAG= True
15.690719930542677
10
M= 1
M= 0
FLAG= True
15.19131886589822
11
M= 66773
M= 47039
M= 0
FLAG= True
15.317225646904472
12
M= 0
FLAG= True
15.637311954028641
13
M= 49652
M= 8317
M= 36230
M= 0
FLAG= True
15.340441456166369
14
M= 0
FLAG= True
15.289165362107525
15
M= 0
FLAG= True
15.495935725085916
16
M= 58898
M= 67075
M= 0
FLAG= True
15.426921046157128
17
M= 0
FLAG= True
15.387962502945015
18
M= 0
FLAG= True
15.5453827744869
19
M= 0
FLAG= True
15.365890384714405
20
M= 54632
M= 0
FLAG= True
15.196484534213726
21
M= 101344
M= 0
FLAG= Tr

M= 9322
M= 60033
M= 39898
M= 13929
M= 2791
FLAG= False
0.0010117563076856295
157
M= 9321
M= 60192
M= 39857
M= 13812
M= 2791
FLAG= False
0.0011233721811282518
158
M= 9321
M= 60385
M= 39820
M= 13656
M= 2791
FLAG= False
0.0012423670733020364
159
M= 9320
M= 60556
M= 39794
M= 13512
M= 2791
FLAG= False
0.0010784326298353786
160
M= 9320
M= 60711
M= 39768
M= 13383
M= 2791
FLAG= False
0.0009890894345858713
161
M= 9320
M= 60847
M= 39735
M= 13280
M= 2791
FLAG= False
0.0009651048908149836
162
M= 9318
M= 61015
M= 39710
M= 13139
M= 2791
FLAG= False
0.001112432117256141
163
M= 9318
M= 61196
M= 39675
M= 12994
M= 2790
FLAG= False
0.001308731048241871
164
M= 9318
M= 61364
M= 39632
M= 12869
M= 2790
FLAG= False
0.0012543379151371808
165
M= 9317
M= 61556
M= 39590
M= 12720
M= 2790
FLAG= False
0.001411477150343697
166
M= 9317
M= 61738
M= 39542
M= 12586
M= 2790
FLAG= False
0.0014065815244517397
167
M= 9317
M= 61917
M= 39502
M= 12447
M= 2790
FLAG= False
0.0013370860595144935
168
M= 9317
M= 62109
M= 39462
M= 12

In [15]:
# for i in range(k):
#     distances[:,i] = np.linalg.norm(X - centers_new[i], axis=1)
    
# clusters = np.argmin(distances, axis = 1)

In [16]:
clusters

# centers_new

array([1, 2, 2, ..., 3, 2, 1])

In [17]:
cont = contingency_matrix(clusters,Y)
print(cont)

[[   86  6887    50  2290     0]
 [56452  2152   806  4334    30]
 [ 3790 33678     9  1430     2]
 [ 6966  3210   130   861    20]
 [   49     0     0  2741     0]]


In [18]:
ans = 0
for i in cont:
    ans = ans + max(i)
purity = ans/len(df)
print(purity)

0.8471974153191557
