In [1]:
from numpy import array
from sklearn.decomposition import PCA
import numpy as np
import pandas as pd
import copy
from sklearn import datasets, svm, metrics
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors.kde import KernelDensity
from sklearn.model_selection import GridSearchCV

In [2]:
df = datasets.load_digits()

n_samples = len(df.images)
data = df.images.reshape((n_samples, -1))

In [3]:
data = StandardScaler().fit_transform(data)

In [4]:
sklearn_pca = PCA(n_components=15)
Y_sklearn = sklearn_pca.fit_transform(data)
Y_sklearn

array([[ 1.91422009, -0.95444007, -3.9459807 , ...,  0.23620658,
        -0.19339795,  0.82403883],
       [ 0.58896824,  0.9246316 ,  3.92487033, ..., -0.02830186,
        -0.36631772, -0.72666955],
       [ 1.30204767, -0.31719626,  3.02335922, ..., -0.55300291,
        -1.00207472, -1.17342377],
       ...,
       [ 1.02257938, -0.14795366,  2.4698685 , ..., -0.43469741,
         0.25093916,  0.30823687],
       [ 1.07605965, -0.3809794 , -2.45563904, ...,  0.14228985,
        -0.78123942,  0.02735016],
       [-1.2577206 , -2.22760256,  0.28362494, ...,  0.08391564,
         0.75610155,  1.81990025]])

In [5]:
params = {'bandwidth': np.logspace(-1, 1, 15)}
grid = GridSearchCV(KernelDensity(), params, cv=5)
grid.fit(Y_sklearn)

/home/vatsal/.local/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=KernelDensity(algorithm='auto', atol=0, bandwidth=1.0, breadth_first=True,
       kernel='gaussian', leaf_size=40, metric='euclidean',
       metric_params=None, rtol=0),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'bandwidth': array([ 0.1    ,  0.13895,  0.19307,  0.26827,  0.37276,  0.51795,
        0.71969,  1.     ,  1.3895 ,  1.9307 ,  2.6827 ,  3.72759,
        5.17947,  7.19686, 10.     ])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [6]:
bd = grid.best_estimator_.bandwidth
bd

0.7196856730011519

In [7]:
kde = KernelDensity(kernel='gaussian', bandwidth=bd).fit(Y_sklearn)
kde.score_samples(Y_sklearn)

array([-15.78233836, -16.29133014, -16.24878752, ..., -16.28829295,
       -16.24562826, -16.34223206])

In [8]:
sklearn_pca = PCA(n_components=27)
Y_sklearn1 = sklearn_pca.fit_transform(data)
Y_sklearn1

array([[ 1.91421505, -0.95449942, -3.94603215, ..., -0.45738558,
         0.71766194,  0.29706641],
       [ 0.58897887,  0.92463728,  3.92475176, ...,  0.78957752,
         0.10717804, -1.63050517],
       [ 1.30203693, -0.31718271,  3.02333512, ..., -0.37984285,
        -0.01163672,  0.32240649],
       ...,
       [ 1.02259945, -0.14791535,  2.4699785 , ..., -0.22886031,
        -1.46667557,  0.07016196],
       [ 1.07605278, -0.38089564, -2.45548897, ..., -0.91268582,
         1.23684394, -0.7730256 ],
       [-1.25769771, -2.22759585,  0.28364642, ..., -0.91176624,
        -0.64108908, -0.13477871]])

In [9]:
params = {'bandwidth': np.logspace(-1, 1, 27)}
grid = GridSearchCV(KernelDensity(), params, cv=5)
grid.fit(Y_sklearn1)

/home/vatsal/.local/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=KernelDensity(algorithm='auto', atol=0, bandwidth=1.0, breadth_first=True,
       kernel='gaussian', leaf_size=40, metric='euclidean',
       metric_params=None, rtol=0),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'bandwidth': array([ 0.1    ,  0.11938,  0.14251,  0.17013,  0.20309,  0.24245,
        0.28943,  0.34551,  0.41246,  0.49239,  0.5878 ,  0.7017 ,
        0.83768,  1.     ,  1.19378,  1.4251 ,  1.70125,  2.03092,
        2.42446,  2.89427,  3.45511,  4.12463,  4.92388,  5.87802,
        7.01704,  8.37678, 10.     ])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [10]:
bd = grid.best_estimator_.bandwidth
bd

0.701703828670383

In [11]:
kde = KernelDensity(kernel='gaussian', bandwidth=bd).fit(Y_sklearn1)
kde.score_samples(Y_sklearn1)

array([-22.64152803, -22.73689488, -22.74039999, ..., -22.74025106,
       -22.73638313, -22.74062944])

In [12]:
sklearn_pca = PCA(n_components=39)
Y_sklearn2 = sklearn_pca.fit_transform(data)
Y_sklearn2

array([[ 1.91421369, -0.9545015 , -3.94603468, ...,  0.08407313,
         0.80473712,  0.02122761],
       [ 0.58898036,  0.92463559,  3.92475531, ..., -0.21940288,
         0.19595015,  0.10859576],
       [ 1.30203906, -0.31718905,  3.02333314, ...,  0.42558691,
        -0.22225561, -1.29563426],
       ...,
       [ 1.02259599, -0.14791104,  2.46997386, ..., -0.53595878,
         0.59584087,  0.39344378],
       [ 1.07605519, -0.38090642, -2.45548685, ...,  0.44398046,
         0.44097064, -0.68788469],
       [-1.25770233, -2.22759097,  0.28362798, ..., -0.26045873,
        -0.37938511,  0.12263919]])

In [13]:
params = {'bandwidth': np.logspace(-1, 1, 39)}
grid = GridSearchCV(KernelDensity(), params, cv=5)
grid.fit(Y_sklearn2)

/home/vatsal/.local/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=KernelDensity(algorithm='auto', atol=0, bandwidth=1.0, breadth_first=True,
       kernel='gaussian', leaf_size=40, metric='euclidean',
       metric_params=None, rtol=0),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'bandwidth': array([ 0.1    ,  0.11288,  0.12743,  0.14384,  0.16238,  0.1833 ,
        0.20691,  0.23357,  0.26367,  0.29764,  0.33598,  0.37927,
        0.42813,  0.48329,  0.54556,  0.61585,  0.69519,  0.78476,
        0.88587,  1.     ,  1.12884,  1.27427,  1.43845,  1.62378,
        1.83298,  2.06914,  2.33572,  2.63665,  2.97635,  3.35982,
        3.79269,  4.28133,  4.83293,  5.45559,  6.15848,  6.95193,
        7.8476 ,  8.85867, 10.     ])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [14]:
bd = grid.best_estimator_.bandwidth
bd

0.6951927961775606

In [15]:
kde = KernelDensity(kernel='gaussian', bandwidth=bd).fit(Y_sklearn2)
kde.score_samples(Y_sklearn2)

array([-29.12544547, -29.15285875, -29.15337458, ..., -29.15338941,
       -29.15333299, -29.15339993])